apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-delivery

resources:
  - namespace.yaml
  - configmap.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - services.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: local-delivery
      app.kubernetes.io/managed-by: kustomize
