apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-delivery-dev

resources:
  - ../../base

namePrefix: dev-

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: backend
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: frontend

configMapGenerator:
  - name: local-delivery-config
    behavior: merge
    literals:
      - APP_ENV=dev
      - LOG_LEVEL=DEBUG
      - CORS_ORIGINS=http://localhost:3000
